import { defineConfig } from 'orval';

/**
 * Comprehensive Orval Configuration Template.
 * Copy and modify this for your project requirements.
 */
export default defineConfig({
  // Name of the API service
  myApi: {
    // Path to the OpenAPI specification
    input: {
      target: './openapi.yaml',
      // validation: true, // Validate the spec before generating
    },
    output: {
      // Where to save the generated code
      target: './src/api/generated/index.ts',
      
      // Where to save the shared types/models
      schemas: './src/api/model',
      
      // Client type: 'fetch', 'axios', 'react-query', 'swr', 'angular', 'zod'
      client: 'react-query',
      
      // File generation mode: 'single', 'split', 'tags', 'tags-split'
      mode: 'tags-split',
      
      // Generate MSW mocks for testing
      mock: true,
      
      // Prettier integration
      prettier: true,
      
      // Clean target directory before generation
      clean: true,
      
      override: {
        // Zod Generation Settings
        zod: {
          generate: {
            schemas: true,
            request: true,
            response: true,
            query: true,
            params: true,
          },
          strict: {
            query: true,
            params: true,
            request: true,
            response: false,
          },
          coerce: {
            query: true,
          },
        },
        
        // React Query Settings (if client: 'react-query')
        query: {
          useQuery: true,
          useMutation: true,
          useInfinite: true,
          useInfiniteQueryParam: 'next_cursor',
          options: {
            queries: {
              staleTime: 1000 * 60 * 5, // 5 minutes
            },
          },
        },
        
        // Global Header injection (static)
        header: (info) => [
          `import { customHeader } from '../header'`,
          `// Generated by Orval v8`,
        ],
      },
    },
  },
});
