import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
// Note: This import path refers to code generated by Orval
import { 
  createPetBodySchema, 
  getPetParamsSchema,
  listPetsQuerySchema 
} from './generated/petstore.zod';

/**
 * Example of using Orval-generated Zod schemas in a Hono server.
 * This ensures that your server-side validation is ALWAYS in sync
 * with your OpenAPI specification.
 */
const app = new Hono();

// Validate query parameters
app.get('/pets', zValidator('query', listPetsQuerySchema), (c) => {
  const query = c.req.valid('query');
  return c.json({ pets: [], query });
});

// Validate path parameters
app.get('/pets/:petId', zValidator('param', getPetParamsSchema), (c) => {
  const { petId } = c.req.valid('param');
  return c.json({ id: petId, name: 'Sample Pet' });
});

// Validate JSON body
app.post('/pets', zValidator('json', createPetBodySchema), (c) => {
  const body = c.req.valid('json');
  return c.json({ message: 'Pet created', pet: body }, 201);
});

export default app;
